#### 1. Import the numpy package as in the name `np` (easy)

In [ ]:
import numpy as np

#### 2. Please print out the numpy version and the configuration (easy)

In [ ]:
print(np.__version__)

1.19.5


#### 3. How can we find the memory size of any array (easy)

In [ ]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


#### 4. Let create a null vector of size 10 (easy)

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Show how to get the documentation of the numpy add function from the command line? (easy)

In [ ]:
print(np.info(np.add))

None


#### 6. Let create a null vector of size 10 but the fifth value which is 1 (easy)

In [ ]:
x = np.zeros(10)
print(x)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (easy)

In [ ]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (i.e., first element becomes last) (easy)

In [ ]:
v  = v [::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Could you define a 3x3 matrix with values ranging from 0 to 8 (easy)

In [ ]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from `[1,2,0,0,4,0]` (easy)

In [ ]:
nums = np.array([1,2,0,0,4,0])
print('original array: ', nums)
indices_non_zero_elements = np.where(nums != 0)[0]
print(indices_non_zero_elements)

original array:  [1 2 0 0 4 0]
[0 1 4]


#### 11. Create a 3x3 identity matrix (easy)

In [ ]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (easy)

In [ ]:
array_3_3_3 = np.random.random((3,3,3))
print(array_3_3_3)

[[[0.96847542 0.42926047 0.30478664]
  [0.52172229 0.12112049 0.7278723 ]
  [0.63676889 0.57238777 0.52513575]]

 [[0.27017648 0.43514636 0.58853729]
  [0.36484649 0.2893217  0.63678127]
  [0.0551839  0.46189681 0.77299327]]

 [[0.91986917 0.46910669 0.84036646]
  [0.63318982 0.52174315 0.23923655]
  [0.43594542 0.25716221 0.01997583]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (easy)

In [ ]:
array_10_10 = np.random.random((10,10))
print(array_10_10)
min_arr, max_arr = array_10_10.min(), array_10_10.max()
print('min: ', min_arr)
print('max: ', max_arr)

[[0.8970572  0.2746739  0.12976206 0.55243475 0.26722855 0.40971038
  0.19750757 0.26967015 0.82092442 0.7639138 ]
 [0.65452073 0.63978414 0.22097596 0.47015596 0.0582159  0.13840703
  0.18067094 0.46114795 0.12904321 0.20045256]
 [0.94060732 0.29058251 0.40328183 0.2756461  0.7954446  0.49299726
  0.94533274 0.99458851 0.07555546 0.79588765]
 [0.10766228 0.21183853 0.55670266 0.97591042 0.20910033 0.44595986
  0.12414819 0.38580482 0.54405894 0.70474201]
 [0.92854485 0.23375754 0.81498055 0.52539279 0.1327349  0.49588928
  0.04242849 0.33798716 0.34312908 0.06193614]
 [0.47825908 0.54427643 0.07034599 0.14526446 0.74590854 0.62689356
  0.45251247 0.33761143 0.65870579 0.64820563]
 [0.4842267  0.23634712 0.65850658 0.68553064 0.30169495 0.48941186
  0.13746319 0.59836438 0.14979185 0.14795086]
 [0.0912209  0.10721065 0.81532632 0.78846536 0.61256315 0.99137061
  0.78862433 0.05173604 0.17091392 0.25073295]
 [0.77378511 0.57053761 0.82825158 0.47759573 0.19343867 0.75334508
  0.564812  

#### 14. Create a random vector of size 30 and find the mean value (easy)

In [ ]:
vector_30 = np.random.random(30)
print(vector_30)
print('mean value: ', vector_30.mean())


[0.57559122 0.07726508 0.63388179 0.08193632 0.22287179 0.31905292
 0.05440391 0.27242266 0.62492429 0.52586972 0.36729618 0.29787481
 0.08649351 0.09282269 0.98062515 0.64845445 0.58616912 0.82224905
 0.84859482 0.5505842  0.74790589 0.08542245 0.93341807 0.35540934
 0.15833174 0.70733252 0.31070393 0.34360354 0.83947693 0.59587849]
mean value:  0.4582288860799609


#### 15. Make a 2d array with 1 on the border and 0 inside (easy)

In [ ]:
array_2d = np.ones((5,5))
print(array_2d)
print("1 on the border and 0 inside in the array")
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (easy)

In [ ]:
existing_arr = np.ones((3,3))
print(existing_arr)
print('0 on the border and 1 inside in the array:')
existing_arr = np.pad(existing_arr, pad_width=1, mode='constant', constant_values=0)
print(existing_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (easy)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (easy)

In [ ]:
matrix_5_5 = np.diag([1,2,3,4,5])
print(matrix_5_5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (easy)

In [ ]:
matrix_8_8 = np.ones((3,3))
print('checkerboard pattern: ')
matrix_8_8 = np.zeros((8,8), dtype=int)
matrix_8_8[1::2,::2] = 1
matrix_8_8[::2,1::2] = 1
print(matrix_8_8)

checkerboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index `(x,y,z)` of the 100th element? (easy)

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (easy)

In [ ]:
matrix_8_8_tile = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(matrix_8_8_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (easy)

In [ ]:
matrix_nor_5_5 = np.random.random((3,3))
print(matrix_nor_5_5)
xmax, xmin = matrix_nor_5_5.max(), matrix_nor_5_5.min()
matrix_nor_5_5 = (matrix_nor_5_5 - xmin)/(xmax - xmin)
print('after normalization: ')
print(matrix_nor_5_5)

[[0.83748516 0.17578685 0.61225418]
 [0.64555481 0.74965167 0.62610874]
 [0.31788902 0.56017595 0.60008145]]
after normalization: 
[[1.         0.         0.65961681]
 [0.70994281 0.86726052 0.68055469]
 [0.21475371 0.58091292 0.64122061]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (easy)

In [ ]:
colorItem = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte, 1), ('a', np.ubyte, 1)])
print(colorItem)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (easy)

In [ ]:
matrix_5_3 = np.random.random((5,3))
print('matrix 5x3:')
print(matrix_5_3)

matrix_3_2 = np.random.random((3,2))
print('matrix 3x2:')
print(matrix_3_2)

real_matrix = np.dot(matrix_5_3, matrix_3_2)
print('real matrix product:')
print(real_matrix)

matrix 5x3:
[[0.4608424  0.8351398  0.06767888]
 [0.83302553 0.16339365 0.20806007]
 [0.92533719 0.34453742 0.60068905]
 [0.59927559 0.92579655 0.48207899]
 [0.70789443 0.16449364 0.29451109]]
matrix 3x2:
[[0.30153765 0.4109902 ]
 [0.1007148  0.05520664]
 [0.73561098 0.57543676]]
real matrix product:
[[0.2728576  0.27445189]
 [0.42069598 0.47111116]
 [0.75559747 0.74498383]
 [0.62856816 0.57481249]
 [0.44666936 0.46949133]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (easy)

In [ ]:
arr_1d = np.arange(11)
print(arr_1d)
print('after negate:')
arr_1d[(3 < arr_1d) & (arr_1d <= 8)] *= -1
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10]
after negate:
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (easy)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (easy)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: ignored

#### 28. What are the result of the following expressions? (easy)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (easy)

In [ ]:
arr_float = np.random.uniform(-10, +10, 10)
print(arr_float)
np.copysign(np.ceil(np.abs(arr_float)), arr_float)
print(arr_float)

[ 0.53512278 -3.05853673 -8.04316392  1.36230127  5.80717146  1.63845267
  7.66089626  0.81331248  9.75191798  5.4051584 ]
[ 0.53512278 -3.05853673 -8.04316392  1.36230127  5.80717146  1.63845267
  7.66089626  0.81331248  9.75191798  5.4051584 ]


#### 30. How to find common values between two arrays? (easy)

In [ ]:
arr_first = np.arange(0,10)
print(arr_first)
arr_second = np.arange(5,15)
print(arr_second)
print(np.intersect1d(arr_first, arr_second))

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (easy)

In [1]:
import numpy as np

data = np.random.random(1000).reshape(10, 10,10) * np.nan

np.seterr(all="ignore")

np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1114: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (easy)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
# false

#### 33. How to get the dates of yesterday, today and tomorrow? (easy)

In [5]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-09-20
Today:  2021-09-21
Tomorrow:  2021-09-22


#### 34. How to get all the dates corresponding to the month of July 2016? (intermediate)

In [6]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

#### 35. How to compute `((A+B)*(-A/2))` in place (without copy)? (intermediate)

In [7]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (intermediate)

In [8]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

print (np.floor(Z))

print (np.ceil(Z)-1)

print (Z.astype(int))

print (np.trunc(Z))

[9. 1. 6. 9. 2. 2. 5. 0. 8. 9.]
[9. 1. 6. 9. 2. 2. 5. 0. 8. 9.]
[9. 1. 6. 9. 2. 2. 5. 0. 8. 9.]
[9 1 6 9 2 2 5 0 8 9]
[9. 1. 6. 9. 2. 2. 5. 0. 8. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (intermediate)

In [9]:
Z = np.zeros((5,5))

Z += np.arange(5)

print(Z)



[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (easy)

In [11]:
def generate():

  for x in range(10):

    yield x

Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)

In [12]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (intermediate)

In [13]:
Z = np.random.random(10)

Z.sort()

print(Z)

[0.01422943 0.04155369 0.195829   0.20938963 0.31703631 0.45171841
 0.60685973 0.61836068 0.64725177 0.76239511]


#### 41. How to sum a small array faster than np.sum? (intermediate)

In [14]:
Z = np.arange(10)

np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (intermediate)

In [15]:
A = np.random.randint(0,2,5)

B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values

equal = np.allclose(A,B)

print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)

equal = np.array_equal(A,B)

print(equal)

False
False


#### 43. Make an array immutable (read-only) (intermediate)

In [16]:
Z = np.zeros(10)

Z.flags.writeable = False

Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (intermediate)

In [17]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[0.42745794 1.13954179 0.65330005 1.28812607 1.01253975 0.58676621
 0.92093597 0.98334401 0.78020146 0.36074032]
[1.48896163 0.96176834 0.55379056 0.73860843 1.04718882 0.17152568
 0.58849349 0.20883098 0.26633377 1.26819432]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (intermediate)

In [18]:
Z = np.random.random(10)

Z[Z.argmax()] = 0

print(Z)

[0.51691791 0.34035589 0.22244045 0.11271376 0.35445727 0.15400444
 0.44095271 0.         0.20573796 0.34870802]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (intermediate)

In [19]:
Z = np.zeros((5,5), [('x',float),('y',float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix `C` `(Cij =1/(xi - yj))` (intermediate)

In [20]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (intermediate)

In [22]:
for dtype in [np.int8, np.int32, np.int64]:

  print(np.iinfo(dtype).min)

  print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:

  print(np.finfo(dtype).min)

  print(np.finfo(dtype).max)

  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (intermediate)

In [25]:
import numpy as np

# np.set_printoptions(threshold=np.nan)
np.set_printoptions(threshold=np.inf, linewidth=np.nan)

Z = np.zeros((16,16))

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (intermediate)

In [26]:
Z = np.arange(100)

v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()

print(Z[index])

14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (intermediate)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (intermediate)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? (intermediate)

#### 54. How to read the following file? (intermediate)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (intermediate)

#### 56. Generate a generic 2D Gaussian-like array (intermediate)

#### 57. How to randomly place p elements in a 2D array? (intermediate)

#### 58. Subtract the mean of each row of a matrix (intermediate)

#### 59. How to sort an array by the nth column? (intermediate)

#### 60. How to tell if a given 2D array has null columns? (intermediate)

#### 61. Find the nearest value from a given value in an array (intermediate)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (intermediate)

#### 63. Create an array class that has a name attribute (intermediate)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (advanced)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (advanced)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (intermediate)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (advanced)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (advanced)

#### 69. How to get the diagonal of a dot product? (advanced)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (advanced)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (advanced)

#### 72. How to swap two rows of an array? (advanced)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (advanced)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (advanced)

#### 75. How to compute averages using a sliding window over an array? (advanced)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (advanced)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (advanced)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (advanced)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (advanced)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (advanced)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (advanced)

#### 82. Compute a matrix rank (advanced)

#### 83. How to find the most frequent value in an array? (advanced)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (advanced)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (advanced)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (advanced)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (advanced)

#### 88. How to implement the Game of Life using numpy arrays? (advanced)

#### 89. How to get the n largest values of an array (advanced)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (advanced)

#### 91. How to create a record array from a regular array? (advanced)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (advanced)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (advanced)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (advanced)

#### 95. Convert a vector of ints into a matrix binary representation (advanced)

#### 96. Given a two dimensional array, how to extract unique rows? (advanced)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (advanced)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (advanced)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (advanced)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (advanced)